Repository canonical/synapse-operator, pull requests merged in 2023-09, with the labels that each got.

#34 Change attributemaps
  synapse_rock/attributemaps/login_ubuntu.py
Labels: Libraries: Out of sync, trivial

#37 Fix SAML entity_id usage
  config.yaml
  src/synapse/workload.py
  tests/integration/conftest.py
  tests/unit/test_synapse_workload.py
Labels: bug, Libraries: Out of sync, trivial

#38 Fix rock to dump the right file
  synapse_rock/rockcraft.yaml
Labels: bug, Libraries: Out of sync, trivial

#30 Add mjolnir support
  .gitignore
  .licenserc.yaml
  CONTRIBUTING.md
  config.yaml
  generate-src-docs.sh
  metadata.yaml
  mjolnir_snap/snapcraft.yaml
  src-docs/api.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/charm_types.py.md
  src-docs/constants.py.md
  src-docs/database_client.py.md
  src-docs/database_observer.py.md
  src-docs/exceptions.py.md
  src-docs/mjolnir.py.md
  src-docs/observability.py.md
  src-docs/pebble.py.md
  src-docs/register_user.md
  src-docs/reset_instance.md
  src-docs/saml_observer.py.md
  src-docs/user.py.md
  src/actions/register_user.py
  src/charm.py
  src/charm_state.py
  src/constants.py
  src/mjolnir.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  src/user.py
  synapse_rock/rockcraft.yaml
  templates/mjolnir_production.yaml
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_mjolnir.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
  tox.ini
Labels: Libraries: Out of sync, complex

#47 Use edge runners for unit test
  .github/workflows/test.yaml
Labels: Libraries: OK, trivial
