Repository canonical/synapse-operator, pull requests merged in 2023-10, with the labels that each got.

#56 Add SMTP configuration
  config.yaml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src/charm.py
  src/charm_state.py
  src/mjolnir.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_database.py
  tests/unit/test_mjolnir.py
  tests/unit/test_reset_instance_action.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, trivial

#65 Fix linting
  src/synapse/api.py
Labels: Libraries: Out of sync, trivial

#67 feat(digests): Enable digest pinning
  renovate.json
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync

#70 Add ca-certificates package
  synapse_rock/rockcraft.yaml
Labels: Libraries: OK, trivial

#78 Add proxy environment variables
  src-docs/charm_state.py.md
  src/charm_state.py
  src/synapse/workload.py
Labels: Libraries: OK, trivial

#79 ci(digest): Add digest pinning
  renovate.json
Labels: Libraries: OK, trivial

#84 Workaround 1 - New issue templates for chat.ubuntu.com
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement_proposal.yml
  .github/ISSUE_TEMPLATE/matrix_bug_report.yml
  .github/ISSUE_TEMPLATE/matrix_enhancement.yml
Labels: Libraries: OK, trivial

#59 Add action to promote a user to an admin
  actions.yaml
  generate-src-docs.sh
  src-docs/api.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/constants.py.md
  src-docs/mjolnir.py.md
  src-docs/register_user.md
  src/actions/__init__.py
  src/actions/register_user.py
  src/charm.py
  src/charm_state.py
  src/mjolnir.py
  src/synapse/__init__.py
  src/synapse/api.py
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tests/unit/test_mjolnir.py
  tests/unit/test_promote_user_admin_action.py
  tests/unit/test_reset_instance_action.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, complex

#85 Fix how exc.response is checked while sending POST request to API
  src/synapse/api.py
Labels: Libraries: OK, trivial

#77 Add enable_password_config
  config.yaml
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, trivial

#89 Change Mjolnir username
  src/mjolnir.py
Labels: Libraries: OK
