Repository canonical/synapse-operator, pull requests merged in 2023-08, with the labels that each got.

#17 Add COS - Grafana integration
  .wokeignore
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/traefik_k8s/v1/ingress.py
  metadata.yaml
  src/grafana_dashboards/synapse.json
  src/observability.py
  src/prometheus_alert_rules/synape.rule
  src/synapse/workload.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK

#20 Fix metadata contents
  metadata.yaml
Labels: Libraries: Out of sync

#26 Remove ops pg lib and pin dependencies
  requirements.txt
Labels: Libraries: Out of sync

#28 fix(libs): Add cosl library as unit test requirement
  tox.ini
Labels: Libraries: Out of sync

#29 chore(libs): Update charm libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/nginx_ingress_integrator/v0/nginx_route.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Labels: Libraries: OK

#19 Add SAML integration
  .woke.yaml
  .wokeignore
  config.yaml
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/saml_integrator/v0/saml.py
  metadata.yaml
  nginx_rock/etc/nginx.conf
  nginx_rock/rockcraft.yaml
  requirements.txt
  src/charm.py
  src/charm_state.py
  src/charm_types.py
  src/constants.py
  src/database_observer.py
  src/pebble.py
  src/saml_observer.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/attributemaps/u1staging.py
  synapse_rock/rockcraft.yaml
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_database.py
  tests/unit/test_register_user_action.py
  tests/unit/test_reset_instance_action.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
  tox.ini
Labels: Libraries: Out of sync

#32 Fix attributemap directory
  src/synapse/workload.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#31 Add PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: Libraries: Out of sync, trivial
