Repository canonical/synapse-operator, pull requests merged in 2024-09, with the labels that each got.

#504 fix: split prometheus targets into two jobs
  src/grafana_dashboards/synapse.json
  src/observability.py
  tests/unit/test_observability.py
  tox.ini
Labels: bug, Libraries: OK, trivial

#500 feat: add limit_remote_rooms_complexity configuration
  config.yaml
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload_configuration.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK

#514 fix: stop Mjolnir if is running in a worker unit
  .github/workflows/integration_test.yaml
  src-docs/mjolnir.py.md
  src/mjolnir.py
  tests/unit/test_mjolnir.py
Labels: bug, Libraries: OK, trivial

#521 Add support for block non admin invites
  config.yaml
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload_configuration.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, urgent

#519 feat: add synapse-invite-checker
  config.yaml
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload_configuration.py
  synapse_rock/rockcraft.yaml
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial, urgent

#525 fix: replace regex for room ids
  src/charm_state.py
  tests/integration/test_charm.py
Labels: bug, Libraries: Out of sync, trivial

#527 feat: bump Synapse to 1.115.0
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#528 Update tutorial
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: Out of sync, trivial

#531 fix: update module and fix configuration
  src/synapse/workload_configuration.py
  synapse_rock/rockcraft.yaml
  tests/unit/test_synapse_workload.py
Labels: bug, Libraries: Out of sync, trivial, urgent

#535 Proposal - chores: remove reset-instance action
  actions.yaml
  docs/how-to/contribute.md
  src-docs/charm.py.md
  src-docs/pebble.py.md
  src/actions/__init__.py
  src/actions/reset_instance.py
  src/charm.py
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/integration/test_s3.py
  tests/unit/test_backup_observer.py
  tests/unit/test_register_user_action.py
  tests/unit/test_reset_instance_action.py
Labels: Libraries: Out of sync, trivial, refactor
