Repository canonical/synapse-operator, pull requests merged in 2024-06, with the labels that each got.

#349 Copy signing keys from main to workers
  src-docs/charm.py.md
  src-docs/database_observer.py.md
  src-docs/media_observer.py.md
  src-docs/pebble.py.md
  src-docs/redis_observer.py.md
  src-docs/saml_observer.py.md
  src-docs/smtp_observer.py.md
  src/charm.py
  src/database_observer.py
  src/media_observer.py
  src/pebble.py
  src/redis_observer.py
  src/saml_observer.py
  src/smtp_observer.py
  src/synapse/.workload.py.swp
  tests/integration/conftest.py
  tests/integration/test_scaling.py
  tests/unit/conftest.py
  tests/unit/test_backup.py
  tests/unit/test_charm_scaling.py
Labels: Libraries: OK, trivial

#375 Skip Mjolnir configuration if not main unit
  src-docs/mjolnir.py.md
  src/mjolnir.py
  tests/unit/test_mjolnir.py
Labels: Libraries: OK, trivial

#378 Reconcile Synapse configuration avoiding restarts from different sources
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/database_observer.py.md
  src-docs/media_observer.py.md
  src-docs/mjolnir.py.md
  src-docs/pebble.py.md
  src-docs/redis_observer.py.md
  src-docs/saml_observer.py.md
  src-docs/smtp_observer.py.md
  src/charm.py
  src/charm_state.py
  src/database_observer.py
  src/media_observer.py
  src/mjolnir.py
  src/pebble.py
  src/redis_observer.py
  src/saml_observer.py
  src/smtp_observer.py
  src/synapse/workload.py
  tests/unit/test_charm.py
  tests/unit/test_charm_scaling.py
  tests/unit/test_charm_state.py
  tests/unit/test_database.py
  tests/unit/test_media_observer.py
Labels: Libraries: OK, complex

#384 Add workers metric target
  src-docs/charm.py.md
  src-docs/observability.py.md
  src-docs/pebble.py.md
  src/charm.py
  src/observability.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/conftest.py
  tests/unit/test_database.py
  tests/unit/test_observability.py
Labels: Libraries: OK, trivial

#388 Reconcile Synapse configuration after every peer relation-changed event
  src-docs/charm.py.md
  src/charm.py
  src/synapse/workload.py
Labels: Libraries: OK, trivial

#390 Fix _on_leader_elected and Mjolnir in case of current leader failure
  src-docs/mjolnir.py.md
  src/charm.py
  src/mjolnir.py
Labels: Libraries: OK, trivial

#395 Fix Grafana panels and add Prometheus alerts
  src/grafana_dashboards/synapse.json
  src/prometheus_alert_rules/synapse.rule
Labels: Libraries: OK

#396 Increase pebble ready check timeout and period
  src-docs/pebble.py.md
  src/pebble.py
Labels: Libraries: OK, trivial

#398 Add workers_ignore_list
  config.yaml
  src-docs/charm_state.py.md
  src/charm_state.py
  tests/unit/test_charm_scaling.py
Labels: Libraries: OK, trivial

#402 Enable tracks for version control
  .github/workflows/publish_charm.yaml
Labels: Libraries: OK, trivial
