Repository canonical/synapse-operator, pull requests merged in 2024-03, with the labels that each got.

#235 Add refresh admin access token when invalid
  src-docs/admin_access_token.py.md
  src-docs/api.md
  src/admin_access_token.py
  src/synapse/__init__.py
  src/synapse/api.py
  tests/integration/test_charm.py
  tests/unit/test_admin_access_token.py
  tests/unit/test_synapse_api.py
Labels: bug, Libraries: OK, trivial

#238 Increase memory alert to 3GB
  src/prometheus_alert_rules/synapse.rule
Labels: Libraries: Out of sync, trivial

#217 Add Synapse Stats Exporter pebble layer
  docs/explanation/charm-architecture.md
  src-docs/observability.py.md
  src-docs/pebble.py.md
  src/charm.py
  src/observability.py
  src/pebble.py
  tests/integration/test_charm.py
  tests/unit/test_database.py
Labels: Libraries: OK, trivial

#216 Use self hosted runners again
  .github/workflows/integration_test.yaml
Labels: Libraries: OK, trivial

#252 Chore/refactaroo for Ops in synapse/workload
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#259 Update docs. CharmHub chat link to Matrix and other minor issues.
  README.md
  docs/how-to/contribute.md
  docs/index.md
  docs/tutorial/getting-started.md
Labels: Libraries: OK, trivial

#245 Create worker configuration if not leader
  src-docs/charm.py.md
  src-docs/database_observer.py.md
  src-docs/pebble.py.md
  src/charm.py
  src/database_observer.py
  src/pebble.py
  src/saml_observer.py
  src/smtp_observer.py
  src/synapse/__init__.py
  src/synapse/workload.py
  templates/worker.yaml
  tests/integration/test_charm.py
  tests/unit/test_admin_access_token.py
  tests/unit/test_anonymize_user_action.py
  tests/unit/test_backup_observer.py
  tests/unit/test_charm.py
  tests/unit/test_charm_scaling.py
  tests/unit/test_database.py
  tests/unit/test_mjolnir.py
  tests/unit/test_reset_instance_action.py
Labels: Libraries: OK, complex

#193 Feat/add irc bridge
  config.yaml
  metadata.yaml
  pyproject.toml
  src-docs/admin_access_token.py.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/database_observer.py.md
  src-docs/irc_bridge.py.md
  src-docs/pebble.py.md
  src/admin_access_token.py
  src/charm.py
  src/charm_state.py
  src/database_observer.py
  src/irc_bridge.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  templates/irc_bridge_production.yaml
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_exceptions.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, complex

#266 Set worker name with unit ID
  src/charm.py
  src/pebble.py
  tests/unit/test_charm_scaling.py
Labels: Libraries: OK, trivial
