Repository canonical/synapse-operator, pull requests merged in 2024-05, with the labels that each got.

#328 Refactor NGINX configuration
  requirements.txt
  src-docs/charm_state.py.md
  src/synapse/workload.py
  templates/abuse_report_location.conf.j2
  templates/main_location.conf.j2
Labels: Libraries: Out of sync, trivial

#341 Verify if configuration has changed before restarting Synapse
  requirements.txt
  src-docs/backup_observer.py.md
  src-docs/charm_state.py.md
  src-docs/database_client.py.md
  src-docs/pebble.py.md
  src/database_client.py
  src/pebble.py
Labels: bug, Libraries: OK, trivial

#337 Fix start.py and Grafana dashboard
  .github/workflows/integration_test.yaml
  .github/workflows/test.yaml
  .licenserc.yaml
  src/grafana_dashboards/synapse.json
  src/smtp_observer.py
  synapse_rock/patches/start.patch
  synapse_rock/rockcraft.yaml
  tests/integration/test_s3.py
Labels: bug, Libraries: OK, trivial

#325 Add test_synapse_scaling_down integration test
  tests/integration/conftest.py
  tests/integration/test_scaling.py
Labels: Libraries: OK, trivial

#352 Enable ident for irc bridge
  config.yaml
  src/charm_state.py
  src/irc_bridge.py
  src/synapse/.workload.py.swp
  src/synapse/workload.py
Labels: Libraries: OK, trivial

#350 Add (basic) loki for (initially) irc bridge logs
  lib/charms/loki_k8s/v1/loki_push_api.py
  metadata.yaml
  src/observability.py
Labels: Libraries: OK, trivial

#354 fix(irc): Point to FQDN
  src/synapse/workload.py
Labels: Libraries: OK, trivial

#336 feat(retention): Add media retention
  src-docs/api.md
  src-docs/pebble.py.md
  src-docs/register_user.md
  src-docs/reset_instance.md
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/test_charm.py
Labels: Libraries: OK, trivial

#356 fix(loki): Use valid key for log files
  src/observability.py
Labels: Libraries: OK, trivial

#367 Fix codespell config
  tox.ini
Labels: Libraries: Out of sync, trivial
