Repository canonical/synapse-operator, pull requests merged in 2024-07, with the labels that each got.

#404 Add alive_check configuration
  config.yaml
  src-docs/api.md
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src-docs/register_user.md
  src-docs/reset_instance.md
  src/charm_state.py
  src/pebble.py
  tests/unit/test_charm.py
Labels: Libraries: OK, trivial

#423 Add workflows for tracks support
  .github/workflows/comment_contributing.yaml
Labels: Libraries: OK, trivial

#425 chore(plugins): Remove irc bridge code
  config.yaml
  metadata.yaml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/irc_bridge.py.md
  src-docs/pebble.py.md
  src/charm.py
  src/charm_state.py
  src/irc_bridge.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  templates/irc_bridge_production.yaml
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, trivial

#433 feat(promo): Publish between 1/ tracks
  .github/workflows/promote_charm.yaml
Labels: Libraries: OK, trivial

#445 Test new workflow
  requirements.txt
Labels: Libraries: Out of sync

#437 docs: add horizontally scale how-to
  docs/how-to/horizontally-scale.md
Labels: documentation, Libraries: OK, trivial

#440 fix: set all units to use the same Prometheus exporter port
  src-docs/charm.py.md
  src-docs/observability.py.md
  src/charm.py
  src/observability.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/integration/test_scaling.py
  tests/unit/test_observability.py
Labels: Libraries: OK
