Repository canonical/synapse-operator, pull requests merged in 2024-11, with the labels that each got.

#565 feat: add matrix-auth integration
  metadata.yaml
  pyproject.toml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/matrix_auth_observer.py.md
  src/charm.py
  src/charm_state.py
  src/matrix_auth_observer.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  src/synapse/workload_configuration.py
  tests/unit/conftest.py
  tests/unit/test_charm_state.py
  tests/unit/test_matrix_auth_integration.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, complex

#577 update ingress lib to v2
  charmcraft.yaml
  lib/charms/traefik_k8s/v1/ingress.py
  lib/charms/traefik_k8s/v2/ingress.py
  src-docs/charm.py.md
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#588 fix: fix synapse units panel
  src/grafana_dashboards/synapse.json
Labels: Libraries: Out of sync, trivial

#594 ISD2762 run reconcile on saml relation broken
  .trivyignore
  src-docs/saml_observer.py.md
  src/saml_observer.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#595 ISD-2736 Make public_baseurl required and render it in homeserver config
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload_configuration.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, complex

#609 Update renovate.json
  renovate.json
Labels: Libraries: Out of sync

#613 remove extra tab for indentation
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial
