Repository canonical/synapse-operator, pull requests merged in 2024-02, with the labels that each got.

#163 Minor fix to restart_synapse()
  src/pebble.py
Labels: Libraries: Out of sync, trivial

#172 Refactor S3 Client for Backup
  src-docs/backup.py.md
  src/backup.py
  src/backup_observer.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/test_backup.py
  tests/unit/test_backup_observer.py
Labels: Libraries: Out of sync, trivial

#169 Add forgotten_room_retention_period=28d as default
  src-docs/pebble.py.md
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/test_charm.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#173 feat(irc-bridge): Add irc config handling
  src/charm_state.py
  src/database_observer.py
  src/irc_bridge.py
  src/synapse/workload.py
  templates/irc_bridge_production.yaml
  tests/integration/test_charm.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#166 feat(irc-bridge): Add irc database
  metadata.yaml
  src/charm.py
  src/charm_state.py
  src/database_observer.py
  src/irc_bridge.py
  src/synapse/workload.py
  templates/irc_bridge_production.yaml
  tests/integration/test_charm.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#183 fix(tests): Bye runner bye
  .github/workflows/integration_test.yaml
Labels: bug, Libraries: Out of sync, trivial

#182 Change Mjolnir web address to fix abuse reports
  templates/mjolnir_production.yaml
  tests/integration/conftest.py
Labels: Libraries: Out of sync, trivial

#181 chore(pytest): Add custom markers
  pyproject.toml
  tests/integration/test_charm.py
Labels: Libraries: Out of sync, trivial

#184 Create backup action
  actions.yaml
  config.yaml
  docs/how-to/backup.md
  src-docs/backup.py.md
  src-docs/backup_observer.py.md
  src/backup.py
  src/backup_observer.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/rockcraft.yaml
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_backup.py
  tests/unit/test_backup_observer.py
  tox.ini
Labels: Libraries: Out of sync

#187 List backups action
  actions.yaml
  src-docs/backup.py.md
  src/backup.py
  src/backup_observer.py
  tests/integration/test_charm.py
  tests/unit/test_backup.py
  tests/unit/test_backup_observer.py
Labels: Libraries: Out of sync, trivial

#167 Add cron service and cleanup script
  .licenserc.yaml
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/cron/cron.weekly/remote_content_empty_directory_cleanup.py
  synapse_rock/rockcraft.yaml
  synapse_rock/scripts/run_cron.py
Labels: Libraries: Out of sync, trivial

#189 Restore backup action
  actions.yaml
  docs/how-to/backup-and-restore.md
  docs/how-to/backup.md
  src-docs/backup.py.md
  src/backup.py
  src/backup_observer.py
  src/synapse/workload.py
  tests/integration/test_charm.py
  tests/unit/test_backup.py
  tests/unit/test_backup_observer.py
Labels: Libraries: Out of sync, trivial

#195 Make admin_access_token available via new class Admin Access Token Service
  pyproject.toml
  src-docs/admin_access_token.py.md
  src-docs/charm.py.md
  src-docs/mjolnir.py.md
  src/admin_access_token.py
  src/charm.py
  src/mjolnir.py
  src/synapse/__init__.py
  src/synapse/admin.py
  tests/unit/conftest.py
  tests/unit/test_anonymize_user_action.py
  tests/unit/test_charm.py
  tests/unit/test_mjolnir.py
  tests/unit/test_promote_user_admin_action.py
Labels: Libraries: Out of sync, complex

#203 Add missing how-to index to documentation
  docs/index.md
Labels: Libraries: Out of sync

#207 Publish doc when promoting the charm
  .github/workflows/promote_charm.yaml
Labels: Libraries: Out of sync

#194 Partition integ tests
  .github/workflows/integration_test.yaml
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/integration/test_cos.py
  tests/integration/test_nginx.py
  tests/integration/test_s3.py
  tox.ini
Labels: Libraries: Out of sync, trivial

#210 Build Synapse Stats Exporter in Synapse rock
  src-docs/charm.py.md
  src/charm.py
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#215 Update synapse/poetry versions, pin version for the rust toolchain
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#197 Remove COS integration test
  .github/workflows/integration_test.yaml
  tests/integration/test_cos.py
Labels: Libraries: Out of sync, trivial

#222 Fix lint error, yield -> yield from
  src-docs/backup.py.md
  src/backup.py
Labels: Libraries: Out of sync, trivial

#219 Add Redis configuration when integrating with Redis charm
  .github/workflows/integration_test.yaml
  docs/reference/integrations.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/charm_types.py.md
  src-docs/pebble.py.md
  src-docs/redis_observer.py.md
  src/charm.py
  src/charm_state.py
  src/charm_types.py
  src/pebble.py
  src/redis_observer.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/integration/test_redis.py
  tests/unit/conftest.py
  tests/unit/test_admin_access_token.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, complex
