Repository canonical/synapse-operator, pull requests merged in 2024-08, with the labels that each got.

#448 feat: replace Synapse Statistics grafana dashboard panels
  src/grafana_dashboards/synapse_statistics.json
Labels: Libraries: OK

#449 fix: add rustup snap
  charmcraft.yaml
Labels: Libraries: OK, trivial

#447 fix: fix call to override_ratelimit
  src/synapse/api.py
  tests/unit/test_synapse_api.py
Labels: Libraries: OK

#446 chore: add gh workflow to check for new releases
  .github/workflows/check_for_new_releases.yaml
Labels: Libraries: OK, trivial

#464 chore: bump Synapse from v1.101.0 to v1.112.0 [ISD-2182]
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#477 feat: add rc_joins_remote_burst_count and rc_joins_remote_per_second
  config.yaml
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src/charm_state.py
  src/mjolnir.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  src/synapse/workload_configuration.py
  tests/unit/test_charm.py
  tests/unit/test_mjolnir.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, trivial

#476 feat: add federation_sender_instances
  src-docs/charm.py.md
  src-docs/pebble.py.md
  src/charm.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  src/synapse/workload_configuration.py
  tests/unit/test_charm_scaling.py
Labels: Libraries: OK, trivial

#493 Update docs
  docs/how-to/backup-and-restore.md
  docs/how-to/configure-smtp.md
  docs/how-to/contribute.md
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: OK, trivial
