Repository canonical/synapse-operator, pull requests merged in 2024-10, with the labels that each got.

#542 fix: replace deprecated ops.main.main for ops.main
  src/charm.py
Labels: Libraries: Out of sync, trivial

#541 chore(refactor): move NGINX to Synapse rock
  docs/explanation/charm-architecture.md
  docs/how-to/contribute.md
  metadata.yaml
  nginx_rock/rockcraft.yaml
  src-docs/charm.py.md
  src/charm.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/etc/abuse_report_location.conf
  synapse_rock/etc/main_location.conf
  synapse_rock/etc/nginx.conf
  synapse_rock/etc/worker_location.conf
  synapse_rock/rockcraft.yaml
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_charm_scaling.py
Labels: Libraries: Out of sync, trivial

#545 Update Synapse workload (rock) with Renovate
  .github/workflows/check_for_new_releases.yaml
  renovate.json
Labels: Libraries: Out of sync

#544 docs: change requirements in tutorial
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: Out of sync

#509 feat(lib): Add matrix auth lib
  lib/charms/synapse/v0/matrix_auth.py
  requirements.txt
  src/actions/register_user.py
  src/charm_state.py
  src/s3_parameters.py
  src/smtp_observer.py
  src/user.py
  synapse_rock/cron/cron.weekly/remote_content_empty_directory_cleanup.py
  tests/unit/test_matrix_plugins_lib.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, complex

#563 chore(refactor): remove fixtures
  src-docs/user.py.md
  tests/integration/conftest.py
Labels: Libraries: Out of sync
