Repository canonical/synapse-operator, pull requests merged in 2024-04, with the labels that each got.

#268 Update NGINX configuration to work with horizontal scaling
  .licenserc.yaml
  nginx_rock/etc/abuse_report_location.conf
  nginx_rock/etc/abuse_report_location.conf.template
  nginx_rock/etc/main_location.conf
  nginx_rock/etc/main_location.conf.template
  nginx_rock/etc/nginx.conf
  nginx_rock/etc/worker_location.conf
  nginx_rock/rockcraft.yaml
  src/charm.py
  src/mjolnir.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  templates/worker.yaml
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_charm_scaling.py
  tests/unit/test_synapse_api.py
Labels: Libraries: OK, trivial

#277 Refactor how to generate worker configuration
  src-docs/admin_access_token.py.md
  src-docs/api.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/database_observer.py.md
  src-docs/mjolnir.py.md
  src-docs/pebble.py.md
  src/pebble.py
  templates/worker.yaml
  tests/unit/conftest.py
Labels: Libraries: Out of sync, trivial

#280 Restart worker for relation departed and relation changed
  src-docs/charm.py.md
  src/charm.py
  tests/unit/test_charm_scaling.py
Labels: Libraries: OK, trivial

#282 Add Synapse scaling integration test
  .github/workflows/integration_test.yaml
  tests/integration/conftest.py
  tests/integration/test_redis.py
  tests/integration/test_scaling.py
Labels: Libraries: OK

#289 Add Synapse Statistics grafana dashboard
  src-docs/database_observer.py.md
  src-docs/pebble.py.md
  src/grafana_dashboards/synapse_statistics.json
Labels: Libraries: OK, trivial

#290 fix(irc): Use irc port in app registration
  .github/workflows/integration_test.yaml
  src/synapse/workload.py
Labels: bug, Libraries: OK, trivial

#284 Set worker_connections as 1024
  nginx_rock/etc/nginx.conf
Labels: Libraries: OK, trivial

#288 Add SynapseProcessNewPulledEventHighCPU
  src/prometheus_alert_rules/synapse.rule
Labels: Libraries: OK, trivial

#296 Enable libjemalloc
  src/synapse/workload.py
  synapse_rock/rockcraft.yaml
  tests/unit/test_charm.py
Labels: Libraries: OK, trivial

#308 Add external access reference
  docs/reference/external-access.md
Labels: Libraries: OK, trivial

#256 Enable S3 Media
  docs/how-to/backup-and-restore.md
  localstack-installation.sh
  metadata.yaml
  src-docs/backup.py.md
  src-docs/backup_observer.py.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/charm_types.py.md
  src-docs/media_observer.py.md
  src-docs/pebble.py.md
  src-docs/s3_parameters.py.md
  src/backup.py
  src/backup_observer.py
  src/charm.py
  src/charm_state.py
  src/charm_types.py
  src/media_observer.py
  src/pebble.py
  src/s3_parameters.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/rockcraft.yaml
  tests/integration/conftest.py
  tests/integration/test_s3.py
  tests/unit/conftest.py
  tests/unit/test_charm_state.py
  tests/unit/test_media_observer.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: enhancement, Libraries: OK, complex

#314 Add enable_email_notifs configuration
  config.yaml
  src-docs/charm_state.py.md
  src/charm_state.py
  src/synapse/workload.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#291 Feat/horizontal scaling
  .github/workflows/integration_test.yaml
  .licenserc.yaml
  docs/reference/integrations.md
  nginx_rock/etc/abuse_report_location.conf
  nginx_rock/etc/abuse_report_location.conf.template
  nginx_rock/etc/main_location.conf
  nginx_rock/etc/main_location.conf.template
  nginx_rock/etc/nginx.conf
  nginx_rock/etc/worker_location.conf
  nginx_rock/rockcraft.yaml
  src-docs/admin_access_token.py.md
  src-docs/api.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/database_observer.py.md
  src-docs/mjolnir.py.md
  src-docs/pebble.py.md
  src/admin_access_token.py
  src/charm.py
  src/charm_state.py
  src/database_observer.py
  src/mjolnir.py
  src/pebble.py
  src/saml_observer.py
  src/smtp_observer.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/integration/test_redis.py
  tests/integration/test_scaling.py
  tests/unit/conftest.py
  tests/unit/test_admin_access_token.py
  tests/unit/test_anonymize_user_action.py
  tests/unit/test_backup_observer.py
  tests/unit/test_charm.py
  tests/unit/test_charm_scaling.py
  tests/unit/test_charm_state.py
  tests/unit/test_database.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_media_observer.py
  tests/unit/test_mjolnir.py
  tests/unit/test_reset_instance_action.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: OK, complex

#301 Move irc bridge away from collect status
  src-docs/api.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/irc_bridge.py.md
  src-docs/pebble.py.md
  src-docs/register_user.md
  src-docs/reset_instance.md
  src/charm.py
  src/charm_state.py
  src/irc_bridge.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/conftest.py
  tests/unit/test_admin_create_user.py
  tests/unit/test_irc_bridge.py
  tests/unit/test_mjolnir.py
Labels: Libraries: OK

#326 ISD-1839 Add logrotate package
  .github/workflows/integration_test.yaml
  nginx_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#315 Add publish_rooms_allowlist config (fix #162)
  config.yaml
  src-docs/api.md
  src-docs/charm_state.py.md
  src-docs/pebble.py.md
  src-docs/register_user.md
  src-docs/reset_instance.md
  src/charm_state.py
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/test_mjolnir.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial
