Repository canonical/synapse-operator, pull requests merged in 2024-01, with the labels that each got.

#129 chore: license year update
  LICENSE
  actions.yaml
  charmcraft.yaml
  config.yaml
  generate-src-docs.sh
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/nginx_ingress_integrator/v0/nginx_route.py
  lib/charms/saml_integrator/v0/saml.py
  metadata.yaml
  mjolnir_snap/snapcraft.yaml
  nginx_rock/rockcraft.yaml
  pyproject.toml
  src/actions/__init__.py
  src/actions/register_user.py
  src/actions/reset_instance.py
  src/charm.py
  src/charm_state.py
  src/charm_types.py
  src/database_client.py
  src/database_observer.py
  src/exceptions.py
  src/mjolnir.py
  src/observability.py
  src/pebble.py
  src/saml_observer.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  src/user.py
  synapse_rock/attributemaps/login_ubuntu.py
  synapse_rock/rockcraft.yaml
  tests/__init__.py
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/__init__.py
  tests/unit/conftest.py
  tests/unit/test_anonymize_user_action.py
  tests/unit/test_charm.py
  tests/unit/test_database.py
  tests/unit/test_mjolnir.py
  tests/unit/test_promote_user_admin_action.py
  tests/unit/test_register_user_action.py
  tests/unit/test_reset_instance_action.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
  tox.ini
Labels: Libraries: Out of sync, trivial

#131 Remove mjolnir_snap directory in favor of mjolnir-snap repository
  mjolnir_snap/snapcraft.yaml
Labels: Libraries: Out of sync, trivial

#127 Add SMTP via the smtp-integrator charm
  .github/workflows/integration_test.yaml
  config.yaml
  docs/how-to/configure-smtp.md
  docs/how-to/contribute.md
  docs/index.md
  docs/reference/integrations.md
  lib/charms/smtp_integrator/v0/smtp.py
  metadata.yaml
  pyproject.toml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/charm_types.py.md
  src-docs/pebble.py.md
  src-docs/smtp_observer.py.md
  src/charm.py
  src/charm_state.py
  src/charm_types.py
  src/pebble.py
  src/smtp_observer.py
  src/synapse/workload.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_smtp_observer.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
  tox.ini
Labels: Libraries: Out of sync, complex

#130 Create integration test to refresh the charm
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
Labels: Libraries: Out of sync, trivial

#135 Add Prometheus alerts
  src/prometheus_alert_rules/synape.rule
Labels: Libraries: Out of sync

#136 Fix Prometheus rule file name and formatting
  src/prometheus_alert_rules/synape.rule
  src/prometheus_alert_rules/synapse.rule
Labels: Libraries: Out of sync, trivial

#142 feat(irc): Add irc bridge
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#145 Create bot_pr_approval.yaml
  .github/workflows/bot_pr_approval.yaml
Labels: Libraries: Out of sync, trivial

#139 Add Synapse backup s3-integration
  .github/workflows/integration_test.yaml
  docs/how-to/contribute.md
  docs/reference/integrations.md
  lib/charms/data_platform_libs/v0/s3.py
  localstack-installation.sh
  metadata.yaml
  requirements.txt
  src-docs/backup.py.md
  src-docs/backup_observer.py.md
  src-docs/charm.py.md
  src/backup.py
  src/backup_observer.py
  src/charm.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_backup.py
  tests/unit/test_backup_observer.py
  tox.ini
Labels: Libraries: Out of sync, complex

#149 Use GitHub runners
  .github/workflows/integration_test.yaml
  tests/integration/conftest.py
Labels: Libraries: Out of sync, trivial

#157 Add SYNAPSE_CONFIG_{PATH,DIR} to the synapse pebble layer env
  src/synapse/__init__.py
  src/synapse/workload.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#156 Fix nginx rockcraft base def
  nginx_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#168 Freeze DatasourcePostgreSQL and SAMLConfiguration
  src/charm_types.py
Labels: Libraries: Out of sync, trivial
