Repository canonical/synapse-operator, pull requests merged in 2025-06, with the labels that each got.

#811 feat: Adding packages needed to build cryptography
  .trivyignore
  charmcraft.yaml
Labels: Libraries: Out of sync

#794 Increase backgroundDelayMS and add safeMode option to Draupnir
  docs/changelog.md
  templates/moderation_production.yaml
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#813 Bump Synapse to 1.130.0
  .trivyignore
  charmcraft.yaml
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#778 Update migration docs
  docs/how-to/migrate-to-mas.md
Labels: documentation, Libraries: Out of sync, trivial

#829 Run config-changed logic in upgrade charm
  src/charm.py
Labels: Libraries: Out of sync, trivial

#837 Add two env vars to s3 command
  .trivyignore
  src/backup.py
Labels: Libraries: Out of sync
