Repository canonical/synapse-operator, pull requests merged in 2025-04, with the labels that each got.

#744 Add enable_media_sync_cleanup configuration
  config.yaml
  docs/changelog.md
  src/backup_observer.py
  src/state/charm_state.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/patches/s3_media_upload.patch
  synapse_rock/rockcraft.yaml
  tests/integration/test_s3.py
  tests/unit/test_backup_observer.py
  tests/unit/test_charm.py
  tests/unit/test_synapse_workload.py
  tests/unit_ops/conftest.py
  tests/unit_ops/test_charm.py
  tox.ini
Labels: Libraries: Out of sync, complex

#748 Add docs for upgrading from latest/edge to 2/edge. Add config option to allow changing the OIDC subject claim
  config.yaml
  docs/how-to/migrate-to-mas.md
  src/auth/mas.py
  src/pebble.py
  src/state/mas.py
  templates/mas_config.yaml.j2
Labels: documentation, Libraries: Out of sync, complex

#769 Refactor default configuration and add default publish publication rules
  .github/pull_request_template.md
  docs/changelog.md
  src/pebble.py
  src/synapse/__init__.py
  src/synapse/workload.py
  src/synapse/workload_configuration.py
  tests/unit/test_charm.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial

#757 ISD-3222 remove custom issuer metadata
  src/auth/mas.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
Labels: Libraries: Out of sync, trivial

#775 bump synapse version for 1/edge
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#777 Bump rockcraft version ( only to rerun charm upload )
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#766 Add Security document
  docs/explanation/cryptography.md
  docs/explanation/security.md
Labels: documentation, Libraries: Out of sync
