Repository canonical/synapse-operator, pull requests merged in 2025-07, with the labels that each got.

#883 Prevent installing deps from synapse-invite-checker
  synapse_rock/rockcraft.yaml
Labels: bug, Libraries: Out of sync, trivial

#820 ISD-3493 Add vale to unit tests and fix some errors after local-audit
  .custom_wordlist.txt
  .github/workflows/test.yaml
  README.md
  docs/how-to/migrate-to-mas.md
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: Out of sync

#890 Add terraform module
  .github/workflows/integration_test.yaml
  .github/workflows/scheduled_integration_test.yaml
  .github/workflows/test_terraform_files.yaml
  .github/workflows/test_terraform_module.yaml
  .gitignore
  renovate.json
  terraform/.tflint.hcl
  terraform/README.md
  terraform/main.tf
  terraform/outputs.tf
  terraform/tests/.tflint.hcl
  terraform/tests/main.tf
  terraform/tests/main.tftest.hcl
  terraform/variables.tf
  terraform/versions.tf
Labels: Libraries: Out of sync, trivial
