Repository canonical/synapse-operator, pull requests merged in 2025-01, with the labels that each got.

#642 Integrate Allure with Synapse
  .github/workflows/integration_test.yaml
  requirements.txt
  tox.ini
Labels: Libraries: Out of sync, trivial

#644 fix matrix-auth v1 publishing
  lib/charms/synapse/v1/matrix_auth.py
Labels: Libraries: Out of sync, trivial

#645 Move allure package to tox.ini
  requirements.txt
  tox.ini
Labels: Libraries: Out of sync, trivial

#647 docs: add changelog (ISD-2719)
  .github/pull_request_template.md
  docs/changelog.md
  docs/how-to/contribute.md
Labels: documentation, Libraries: Out of sync

#649 Remove matrix-auth v0 and fix tests
  lib/charms/synapse/v0/matrix_auth.py
  src-docs/matrix_auth_observer.py.md
  src/matrix_auth_observer.py
  tests/unit/test_matrix_plugins_lib.py
Labels: Libraries: Out of sync, trivial

#620 ISD-2817 Add mas to pebble plan
  .trivyignore
  actions.yaml
  config.yaml
  docs/explanation/moderation-and-spam-control.md
  pyproject.toml
  src-docs/admin_access_token.py.md
  src-docs/charm.py.md
  src-docs/mjolnir.py.md
  src-docs/pebble.py.md
  src/actions/__init__.py
  src/actions/register_user.py
  src/admin_access_token.py
  src/auth/mas.py
  src/charm.py
  src/mjolnir.py
  src/pebble.py
  src/state/charm_state.py
  src/state/mas.py
  src/state/validation.py
  src/synapse/__init__.py
  src/synapse/admin.py
  src/synapse/api.py
  src/synapse/workload.py
  src/synapse/workload_configuration.py
  synapse_rock/etc/nginx.conf
  synapse_rock/rockcraft.yaml
  templates/mas_config.yaml.j2
  templates/mjolnir_production.yaml
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_action.py
  tests/unit/test_admin_access_token.py
  tests/unit/test_admin_create_user.py
  tests/unit/test_anonymize_user_action.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_mas.py
  tests/unit/test_mjolnir.py
  tests/unit/test_promote_user_admin_action.py
  tests/unit/test_register_user_action.py
  tests/unit/test_smtp_observer.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, complex

#654 update codeowners to assigned team members
  CODEOWNERS
Labels: Libraries: Out of sync, trivial

#656 Update renovate.json
  renovate.json
Labels: Libraries: Out of sync

#657 Update metadata.yaml
  metadata.yaml
Labels: Libraries: Out of sync

#666 Update charmcraft
  .trivyignore
  charmcraft.yaml
  lib/charms/synapse/v1/matrix_auth.py
Labels: Libraries: Out of sync, trivial
