Repository canonical/synapse-operator, pull requests merged in 2025-03, with the labels that each got.

#713 Change synapse-invite-checker URL
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#621 ISD-2761 Add oauth lib and requirer
  .trivyignore
  charmcraft.yaml
  lib/charms/hydra/v0/oauth.py
  metadata.yaml
  src/auth/mas.py
  src/charm.py
  src/pebble.py
  src/state/mas.py
  templates/mas_config.yaml.j2
  tests/unit/conftest.py
  tests/unit/test_action.py
  tests/unit/test_mas.py
Labels: Libraries: Out of sync, complex

#725 Update backup-and-restore.md
  docs/how-to/backup-and-restore.md
Labels: documentation, Libraries: Out of sync

#727 Remove pylint useless-suppression and enable it in tox.ini
  src/backup.py
  src/state/charm_state.py
  src/state/validation.py
  src/synapse/api.py
  src/user.py
  tests/integration/any_charm.py
  tests/integration/test_charm.py
  tests/integration/test_matrix_auth.py
  tests/integration/test_s3.py
  tests/unit/conftest.py
  tests/unit/test_backup.py
  tests/unit/test_synapse_workload.py
  tox.ini
Labels: Libraries: Out of sync, trivial

#724 Add charm architecture diagram
  docs/explanation/charm-architecture.md
Labels: documentation, Libraries: Out of sync

#714 Add moderation service
  .github/pull_request_template.md
  config.yaml
  docs/changelog.md
  docs/how-to/contribute.md
  generate-src-docs.sh
  pyproject.toml
  src-docs/backup.py.md
  src-docs/backup_observer.py.md
  src-docs/charm.py.md
  src-docs/charm_types.py.md
  src-docs/database_client.py.md
  src-docs/database_observer.py.md
  src-docs/exceptions.py.md
  src-docs/matrix_auth_observer.py.md
  src-docs/media_observer.py.md
  src-docs/observability.py.md
  src-docs/pebble.py.md
  src-docs/redis_observer.py.md
  src-docs/s3_parameters.py.md
  src-docs/smtp_observer.py.md
  src-docs/user.py.md
  src/auth/mas.py
  src/charm.py
  src/loki_alert_rules/synapse_mjolnir_error_fond.rule
  src/loki_alert_rules/synapse_moderation_error_found.rule
  src/pebble.py
  src/state/charm_state.py
  src/synapse/__init__.py
  src/synapse/workload.py
  synapse_rock/rockcraft.yaml
  templates/moderation_production.yaml
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tests/unit/test_synapse_workload.py
  tox.ini
Labels: Libraries: Out of sync, complex

#733 refactor: Move actions to a separate file
  src/actions.py
  src/charm.py
Labels: Libraries: Out of sync, trivial

#742 Upgrade synapse to 1.127.1 to fix CVE-2025-30355
  .trivyignore
  synapse_rock/rockcraft.yaml
Labels: Libraries: Out of sync

#732 refactor: Remove API module
  pyproject.toml
  src/charm.py
  src/synapse/__init__.py
  src/synapse/api.py
  src/synapse/workload.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_synapse_api.py
  tests/unit/test_synapse_workload.py
Labels: Libraries: Out of sync, trivial
